# Generated by Django 4.2.20 on 2025-05-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_subject_comment_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='subjects',
            new_name='subject',
        ),
    ]
